### ISSUE TITLE
나의 비공개 리스트가 탐색에서는 보이고 피드에서는 안보이는 이슈

### ISSUE THREAD

**Issue by seoyoung-min** [8-Sprinters/ListyWave-front#104]
### 🐞 버그 설명
제 리스트가 탐색에서는 보이고 피드에서는 안 보입니다! 왜 그럴까요 🥹

### ✅ 예상 결과

비공개 리스트가 내 콜라보리스트 목록에만 보인다.

### 1번 이슈. 내 비공개 리스트가 트렌딩리스트 + 검색 결과에서 보인다
![비공개리스트가 탐색에](https://github.com/8-Sprinters/ListyWave-front/assets/144652458/2f10619f-e54e-4032-9e2e-0216a0cd0b8c)

<img width="417" alt="Screenshot 2024-02-25 at 20 52 05" src="https://github.com/8-Sprinters/ListyWave-front/assets/144652458/2c95539c-88a2-4ba9-a5eb-04a0be37cfd1">

### 2번 이슈. 내 비공개 리스트가 마이피드에서 안 보인다 (105번 리스트에 해당. 정확한 에러 발생 루트를 모르겠습니다! 같이 파악 필요합니다.)
![비공개리스트가 없음](https://github.com/8-Sprinters/ListyWave-front/assets/144652458/a930f49f-827a-4015-855d-c2fbdee765b4)

### 💻 버그 시뮬레이션

.

### 🌏 환경

IOS: 17.2.1 / iPhone12Pro

**Comment by ParkSohyunee** [comment]
서영님, 혹시 제가 확인한 바로 아래와 같이 보이는데요, 혹시 음.. 마이피드 쪽은 어디부분이 문제인것일까요?!

- 비공개 마이리스트 생성 시, 마이피드에 비공개 표시되어 보임 (나만)
- 비공개 콜라보리스트 생성 시, 마이콜라보피드에 비공개 표시되어 보임 (나만)
  - 서영님과 만든 비공개 콜라보 리스트, 서영님 피드에서 안보임(내가 볼때)
  - 망고용과레모네이드 비공개 콜라보 리스트, 내 피드에서 보임(저의 피드)
- 비공개 마이,콜라보 리스트 탐색페이지 트렌딩 노출(모두?)
- 검색페이지에 노출(나만)
