### ISSUE TITLE
리스트 아이템 순위 수정시 마이피드 전체 목록 조회 순서 오류

### ISSUE THREAD

**Issue by ParkSohyunee** [8-Sprinters/ListyWave-front#116]
### 🐞 버그 설명

- 아이템 순위를 수정하고, 마이피드에서 데이터를 불러오면 랭킹의 변동사항이 없어서 순서가 뒤바뀌는 현상으로 보여진다.

### ✅ 예상 결과

- 순위가 바뀔때마다 순서대로 보여지기

### ❗ 실제 결과

- 봄, 여름, 가을, 겨울 순서대로 아이템 생성
- 리스트 상세에 잘 나옴
- 리스트 수정하면서 여름, 가을, 겨울, 봄으로 순위 변경
- 리스트 상세에 잘 나옴
- 마이피드에서 순위가 뒤바뀜
  - 바뀐 순서대로 배열에 순차적으로 response를 받아오고 있으나, 순위, 순서가 바뀌는 것 같습니다.
- 추가로, 리스트를 수정할때마다 아이템이 새로 생성되고 있는 것 같습니다,

![Feb-26-2024 00-58-55](https://github.com/8-Sprinters/ListyWave-front/assets/124856726/218d5770-ef11-4ff5-90c0-f4eddd9f23bb)

### 💻 버그 시뮬레이션

.

### 🌏 환경

- 모바일 브라우저 동일

**Comment by kdkdhoho** [comment]
@ParkSohyunee 확인했습니다! 마이 피드에서 순위 정렬하는건 오늘 중으로 구현하겠습니다!

그리고 아이템의 순위가 변동될 때 새로운 아이템이 생성되는 것이 맞습니다. 혹시 장애의 원인이 되거나 하는 현상일까요??
