### ISSUE TITLE
검색 결과에 '아이템'은 포함되지 않는 문제

### ISSUE THREAD

**Issue by seoyoung-min** [8-Sprinters/ListyWave-front#117]
### 🐞 버그 설명

현재 검색 키워드가 '아이템'에 포함 될 경우는 보여주지 않는다.

**정책** 타이틀(제목) > 라벨 > 아이템
**API명세** 타이틀>소개>라벨
**수정방향**타이틀>소개>라벨>아이템

### ✅ 예상 결과

.

### ❗ 실제 결과

.

### 💻 버그 시뮬레이션

.

### 🙋🏻 More

본인이 좋아하는 아이템을 좋아하는 다른 사람을 찾는 (취향을 비슷한 사람을 찾는) 데에 중요한 부분이 될 것 같습니다!

**Comment by kanglocal** [comment]
동호님께서 수정해주셨다고 하십니다!! 👍 👍 👍 👍 👍 👍 👍 👍
