### ISSUE TITLE
(참고) 탈퇴한 회원 로그인 후 다른 이메일로 로그인 시도하려고 하지만 하지 못하는 이슈

### ISSUE THREAD

**Issue by seoyoung-min** [8-Sprinters/ListyWave-front#128]
### 🐞 버그 설명

카카오쪽 문제인 것 같고 크게 발생할 상황이 없는 이슈라고 생각합니다.
이러한 이슈, 사항이 있다는 것을 공유드리기 위해 작성합니다.
(오히려 자동로그인/계정유지 기능은 장점이 더  많다고  생각합니다!)

탈퇴한 회원으로 로그인 한 후,
다른 이메일로 로그인 하려고 '카카오 로그인' 버튼을 누르지만
바로 '탈퇴한 회원입니다'가 나와서 하지 못하는 이슈

### ✅ 예상 결과

로그인 '에러'가 났을 경우
해당 계정 유지가 되지 않아 바로 다른 계정으로 로그인할 수 있다.

### ❗ 실제 결과

로그인 '에러'가 났음에도
로그인 후 일정 기간 동안 해당 로그인 기록이 유지되어,
다른 계정으로 로그인하기가 어렵다.

https://github.com/8-Sprinters/ListyWave-front/assets/144652458/14a41634-a1f8-483f-8f53-b6c83472840d

### 💻 버그 시뮬레이션

1. 탈퇴한 계정으로 로그인 한다
2. 탈퇴한 회원 페이지가 뜬다.
3. 홈으로 돌아가기 버튼을 누른다.
4. 로그인/회원가입  버튼을 누른다.
5. 카카오톡으로 로그인하기를 누른다.
6. 바로 이전에 작성했던 계정으로 로그인이 시도되며, 이에 따라 탈퇴한 회원 페이지로 이동한다.

### 🙋🏻 More
참고: https://devtalk.kakao.com/t/api/123186

**Comment by ParkSohyunee** [comment]
서영님, 한번 시크릿모드에서 테스트해봐도 좋을 것 같아요! 카카오가 캐싱을 엄청 잘해놔서 소용없을 수도 있겠지만 일정기간 후에는 다시 로그인 시도할 수 있을것으로 생각합니다! 첨부해주신 [카카오 계정과 함께 로그아웃 기능]이 아니라서 안될수도 있을 것 같네요ㅠㅠ 
공유 해 주셔서 감사합니다!! 👍🌈

**Comment by seoyoung-min** [comment]
@ParkSohyunee 
시크릿모드를 생각 못했는데, 말씀주셔서 정말 감사합니다!
덕분에 바로 새로운 이메일로 로그인하여 테스트를 진행할 수 있게 됐습니다!!🥹
정말 감사합니다!!

**Comment by kdkdhoho** [comment]
@seoyoung-min 오.. 그러고보니 회원탈퇴하면 카카오 인증 서버 쪽으로 로그아웃 요청을 보내야하겠네요..! 개발자가 아닌 사용자는 분명 서비스 이용에 불편함이 있을 것 같아요.
해당 부분은 서버에서 처리하겠습니다!

**Comment by kdkdhoho** [comment]
@seoyoung-min 회원 탈퇴 시 카카오 인증 서버와 로그아웃 되도록 처리했습니다!
