### ISSUE TITLE
온보딩 input 길이 버그

### ISSUE THREAD

**Issue by seoyoung-min** [8-Sprinters/ListyWave-front#131]
### 🐞 버그 설명

리스트 타이틀/ 아이템 타이틀에 들어가는 input요소의 width가 커지지 않습니다.

### ✅ 예상 결과

1. 타이틀이 길어지면 박스를 꽉 채울 정도의 width를  갖는다.
2. 타이틀이 길더라도 모두 노출된다.

### ❗ 실제 결과

- 리스트 타이틀
녹화가 날라가 앞에 '리스트  타이틀' 입력 부분 gif는 없습니다ㅠ
input이 살짝 늘어난 이후에는 width가 늘어나거나, 두 줄이 된 다거나 하지 않습니다.

- 아이템 타이틀
input이 선 끝까지 가지 않았음에도 잘립니다.
<img width="145" alt="Screenshot 2024-02-27 at 01 34 51" src="https://github.com/8-Sprinters/ListyWave-front/assets/144652458/bf371a31-4878-4af8-807d-7323ad6b72e5">

### 💻 버그 시뮬레이션

- 최초 로그인 후 온보딩 과정을 거침

### 🌏 환경

IOS: 17.2.1 / iPhone12Pro

**Comment by ParkSohyunee** [comment]
의견 주셔서 감사합니다 서영님~!!!
모두가 처음 진입하는 온보딩인만큼 수정을 하는 것이 좋을 것 같습니다! 
우선 2,3번 먼저 내일 2시까지 수정하고 1번은 화, 수 중으로 좀더 고민해보고 수정반영하겠습니당🎨

1. 리스트 타이틀 : 뭔가 밑줄을 추가로 길게 넣거나, 배경색을 입히거나 등등의 방법을 추가해도 좋을 것 같습니다.
2. 아이템 타이틀 : 이 부분은 width: 100%로 수정하는게 맞는 것 같습니다.
3. 저도 추가 수정방향(님, 타이틀) 다 좋습니다~!
