### ISSUE TITLE
내가 만든 리스트 접근권한이 없어서 수정하지 못하는 이슈

### ISSUE THREAD

**Issue by ParkSohyunee** [8-Sprinters/ListyWave-front#137]
### 🐞 버그 설명

- 내가 만든 리스트의 순위를 수정하려고 했는데, 접근 권한이 없어서 수정되지 않습니다.

### ✅ 예상 결과

- 내가 만든 리스트는 수정할 수 있다.

### ❗ 실제 결과

![image](https://github.com/8-Sprinters/ListyWave-front/assets/124856726/b98d1952-d1a8-40c9-a168-bdc828aa523c)

### 💻 버그 시뮬레이션

.

**Comment by seoyoung-min** [comment]
> @seoyoung-min 서영님, 이 부분 백엔드 이슈 맞을까요? 아니면 수정 시 프론트엔드 코드가 바뀌면 수정되는 부분일까요?
> 
> 비슷한 이슈가 있었던 것 같은데 찾지 못하여 확인차 여쭤봅니당,,

내가 만든 리스트(콜라보X)는 제가 테스트 했을 때 까지는 잘 수정 됐던 것으로 보아, 무언가 잘못된 것 같습니다!
아직 정확한 원인 파악을 해보진 않았는데, 403에러가 뜰만한 이유는 프론트 쪽에 크게 없을 것 같아, 아마 백엔드 쪽에서 한 번 봐주셔야 할 것 같습니다'ㅜㅜ!!

**Comment by kdkdhoho** [comment]
@ParkSohyunee 이거 아마 저희 쪽 실수 같습니다..!
확인해서 말씀드릴게요!

**Comment by ParkSohyunee** [comment]
동호님께서 처리 완료!!
