### ISSUE TITLE
알림 - 전체 읽음으로 표시 기능

### ISSUE THREAD

**Issue by Eugene-A-01** [8-Sprinters/ListyWave-front#157]
### 카테고리

- [ ]  질문하기/도움받기
- [ ]  에러/버그 등 제보하기
- [x]  개선점 제안하기
- [ ]  blocked 상태임을 알리기

<br>

### 내용

알림을 한번에 읽음으로 표시할 수 있는 기능이 있다면 좋겠습니다.
항상 빨간 점이 떠있어서 들어가보게 되네요!!

<br>

**Comment by seoyoung-min** [comment]
저도 추가 기능으로 필요하다고 생각했었습니다!!
요거,,,  시간 나는대로 해보겠습니다!!
제안 감사드려용~~
