### ISSUE TITLE
온보딩 - 홈화면 바로가기 추가 유도하기

### ISSUE THREAD

**Issue by Eugene-A-01** [8-Sprinters/ListyWave-front#178]
### 카테고리

- [ ]  질문하기/도움받기
- [ ]  에러/버그 등 제보하기
- [x]  개선점 제안하기
- [ ]  blocked 상태임을 알리기

<br>

### 내용

온보딩에서 홈화면에 바로가기(앱 아이콘)를 추가하도록 유도하는 단계가 있었으면 좋겠습니다!!

**Comment by ParkSohyunee** [comment]
📌 PWA에서 앱 다운로드 및 홈화면 추가하기가 설정됨에 따라 해당 이슈는 close 하겠습니다.
