### ISSUE TITLE
리스트 이미지 저장 시 이미지 그림자 이슈

### ISSUE THREAD

**Issue by seoyoung-min** [8-Sprinters/ListyWave-front#72]
### 🐞 버그 설명

이미지가 있는 리스트 저장 시, 이미지의 그림자가 많이 깨져서 저장됩니다!

<img width="300"  src="https://github.com/8-Sprinters/ListyWave-front/assets/144652458/7a06ce28-e59d-412a-9cc5-3555adcd9d27">

### ✅ 예상 결과

서비스에서 보이는 대로 그림자가 나와야 할 것 같아요!
<img width="300"  src="https://github.com/8-Sprinters/ListyWave-front/assets/144652458/9b6a88c6-d8bf-4a08-a07c-f4e0e2fd2703">

### ❗ 실제 결과

.

### 💻 버그 시뮬레이션

이미지 저장 후 확인

### 🌏 환경

IOS: 17.2.1 / iPhone 12 Pro

**Comment by kanglocal** [comment]
제가 테스트했을때엔 정상동작중입니다..ㅠㅠㅠ
