### ISSUE TITLE
리스트 비공개 또는 삭제시 알림목록에 Null로 표시되는 현상 

### ISSUE THREAD

**Issue by ParkSohyunee** [8-Sprinters/ListyWave-front#74]
### 🐞 버그 설명

알림 목록에서 null로 표기되는 현상 발견

### ✅ 예상 결과

리스트가 삭제되거나 비공개 처리되는 경우에도 알림에서는 그대로 나와야 함
(* 눌렀을때 모달은 제대로 동작)

📌 또는, 알림에 비공개 또는 삭제처리 된 리스트입니다. 메세지로 대체하기!! 

### ❗ 실제 결과

![스크린샷 2024-02-24 오후 8 05 46](https://github.com/8-Sprinters/ListyWave-front/assets/124856726/32f9eaa8-6bfd-48e2-92ab-91fc52021a73)

### 💻 버그 시뮬레이션

.

### 🌏 환경

- Mobile: 갤럭시 z플립 3
- 브라우저: Chrome

### 🙋🏻 More

null null 해

**Comment by seoyoung-min** [comment]
이슈 해결상황
: 리스트 삭제 됐을 경우 관련 알림 모두 삭제 되는 것으로 수정을 했습니다!
오늘 오후 5시 정도 이전에 생성된 리스트의 경우에는 지금도 삭제하면 'null'로 표기가 될 것이고,
만약 그 이후 생성된 리스트에 대한 알림은 리스트 삭제시 알림도 모두 삭제 됩니다!

우선 이렇게 처리 되는 것 괜찮을까요??

"리스트가 삭제되거나 비공개 처리되는 경우에도 알림에서는 그대로 나와야 함"
"또는, 알림에 비공개 또는 삭제처리 된 리스트입니다. 메세지로 대체하기!!"
ㄴ 먄약 알림이 남아있는 경우, 
아직 알림을 안 읽은 상태에서  리스트 삭제 시 , 알림  확인 표시를 위해서는 '삭제 또는 비공개 처리된 리스트입니다' 모달 이 뜨는 페이지를 여러번 봐야합니다! 만약 알림이 남아있는 게 더 낫다고 한다면 모든 알림을 한 번에 확인 처리하는 기능을 도입해야 좋을 것 같습니다!!

**Comment by seoyoung-min** [comment]
@ParkSohyunee 
이 이슈는 해결 처리 하지만,
저도 모든 알림 처리 있으면 좋겠다는 생각도 있어서, 
모든 알림 한번에 처리하는 기능도 추가 기능 목록에 살포시 넣어두도록  하겠습니다!!
