### ISSUE TITLE
(제안) 비공개/삭제 된 리스트 페이지의 모달 '확인' 클릭 시 탐색으로 리다이렉트 수정

### ISSUE THREAD

**Issue by seoyoung-min** [8-Sprinters/ListyWave-front#84]
### 🐞 버그 설명

비공개/삭제 된 리스트 모달에서 '확인'을 클릭 시 탐색으로 리다이렉트 됩니다.

### ✅ 예상 결과

이전  페이지로 이동하는 것을 기대했습니다.
모달의 '확인' 버튼에 'router.back' 등 으로 뒤로 보내면 좋을 것 같습니다!

### ❗ 실제 결과

탐색 페이지로 리다이렉트 된다.

https://github.com/8-Sprinters/ListyWave-front/assets/144652458/35a8bbec-d91a-46bb-986f-4883d781693c

### 💻 버그 시뮬레이션

마이피드 > 리스트 삭제 > 마이피드 > 삭제한 리스트 클릭  > 리스트 상세 > 안내 모달 > **확인 클릭 > 탐색**

### 🌏 환경

IOS: 17.2.1 / iPhone 12 Pro

**Comment by ParkSohyunee** [comment]
서영님, 만약 리스트 삭제 후 마이피드에 반영이 바로 된다면, 위의 플로우는 실행하지 않아도 되는 것으로 이해했는데 맞을까요?!

**Comment by seoyoung-min** [comment]
@ParkSohyunee 어머 그러네요!! 살포시 close 해두겠습니다...ㅎㅎ
