### ISSUE TITLE
리스트 상세 페이지 셀프 콜렉트 못하게 막기

### ISSUE THREAD

**Issue by Eugene-A-01** [8-Sprinters/ListyWave-front#90]
### 🐞 버그 설명

![Uploading IMG_9559.jpeg…]()

탐색 트렌딩 리스트에서
내가 만든 리스트를 클릭해서 들어가면
수정 케밥 아이콘이 안뜹니다.

### ✅ 예상 결과

탐색페이지를 통해 들어간 내가만든 리스트의 상세조회 페이지에서도 수정 케밥버튼이 있어야할것 같고 셀프콜렉트도 안되게 막아야할거같습니다.

### ❗ 실제 결과

제가 작성자인지 탐색->상세 루트로 접속시
사용자가 작성자인지 판단하는 로직이 적용되어야할거같습니다

### 💻 버그 시뮬레이션

탐색페이지에서 내가 쓴 리스트 발견
클릭해서 상세조회 페이지로 접속함
수정이나 삭제를 위한 케밥버튼 이없고 셀프콜렉트가 가능했음.

### 🌏 환경

IOS Chrome

**Comment by Nahyun-Kang** [comment]
@Eugene-A-01  엇 유진님 저는 뜨는데 이상하네용..! 🤔 혹시 다른 리스트들도 확인해볼 수 있을까요?!

**Comment by Nahyun-Kang** [comment]
@kanglocal 현지님! 이슈 수정해두었습니당 확인해주시면 감사드리겠습니다..!
