### ISSUE TITLE
로그아웃 실패

### ISSUE THREAD

**Issue by seoyoung-min** [8-Sprinters/ListyWave-front#92]
### 🐞 버그 설명

로그아웃에 실패합니다.

### ✅ 예상 결과

로그아웃을 한다

### ❗ 실제 결과

로그아웃에 실패한다
![IMG_8459](https://github.com/8-Sprinters/ListyWave-front/assets/144652458/644cc968-4b23-4dc6-a29d-36b2f8e59ba3)

### 💻 버그 시뮬레이션

로그아웃을 시도했으나 실패했습니다

### 🌏 환경

IOS: 17.2.1 /iPhone12Pro

**Comment by ParkSohyunee** [comment]
서영님, 혹시 로그인 했다가 로그아웃 해도 로그아웃이 안되는 것일까요? 
여쭤보는 이유는 이미 브라우저 등에서 로그아웃된 상태인 사용자가 로그아웃을 시도했을때 발생하는 문제인 것 같아서 확인차 여쭤봅니다.

**Comment by seoyoung-min** [comment]
@ParkSohyunee 소현님, 현재 로그인 되어있는 상태로 보입니다! 마이피드/알림 등 접근이 가능하나 로그아웃은 불가능한 상태입니다!

**Comment by ParkSohyunee** [comment]
> @ParkSohyunee 소현님, 현재 로그인 되어있는 상태로 보입니다! 마이피드/알림 등 접근이 가능하나 로그아웃은 불가능한 상태입니다!

넵 서영님, 로그아웃해도 토큰이 만료되지 않아서 발생한 문제로 보입니다, 백엔드쪽에 확인 요청드리겠습니다!! 감사합니다.🥰

**Comment by ParkSohyunee** [comment]
2/27, 벡엔드에서 로그아웃 실패 시, 400 Bad request 응답 오는 것으로 해결 완료!
