### ISSUE TITLE
히스토리페이지 그래프/버전 선택 탭 위치 고정

### ISSUE THREAD

**Issue by seoyoung-min** [8-Sprinters/ListyWave-front#95]
### 🐞 버그 설명

히스토리 페이지의 그래프/버전 선택 탭의 위치가 고정되어 다른 요소와 겹치는 이슈가 발생했습니다.

### ✅ 예상 결과

스크롤될때 같이 올라간다.

### ❗ 실제 결과

https://github.com/8-Sprinters/ListyWave-front/assets/144652458/0358f2a8-94b8-44c3-84ce-78f74e651f9f

### 💻 버그 시뮬레이션

히스토리 페이지 방문후 스크롤

### 🌏 환경

IOS: 17.2.1 / iPhone12Pro

**Comment by Eugene-A-01** [comment]
일부러 헤더와 그래프/버전은 navigation 바처럼 위에 고정되어있게 구현했는데
맨 위에서만 그래프/버전을 확인할 수 있게 바꾸는게 나을까요?

(+ 서영님께서 남겨주신 이 QA에서 제일 놀란점은 바로 헤더가 상단 고정이 안되었다는 사실......................😱)
